vim.api.nvim_set_keymap("n", "<Leader>ff", [[<Cmd>lua require('telescope.builtin').find_files()<CR>]], {noremap = true})
vim.api.nvim_set_keymap("n", "<Leader>fg", [[<Cmd>lua require('telescope.builtin').live_grep()<CR>]], {noremap = true})
vim.api.nvim_set_keymap("n", "<Leader>fb", [[<Cmd>lua require('telescope.builtin').buffers()<CR>]], {noremap = true})
vim.api.nvim_set_keymap("n", "<Leader>fhf", [[:Telescope find_files hidden=true <cr>]], {noremap = true})
vim.api.nvim_set_keymap("n", "<Leader>fhh", [[<Cmd>lua require('telescope.builtin').help_tags()<CR>]], {noremap = true})
